spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hj_manage_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      #DM
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://192.168.3.138:5236
#      username: SYSDBA
#      password: SYSDBA
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://32.1.8.89:5237
#      username: SYSDBA
#      password: SYSDBA
#      #Oracle
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521:xe
#      username: renren_security
#      password: 123456
#      #SQLServer
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=security_enterprise
#      username: sa
#      password: 123456
#      #postgresql
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/security_enterprise
#      username: postgres
#      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        #url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        config:
          enabled: false
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: false

biz-properties:
#  fileUploadPath: /home/project/Contract
  fileUploadPath: C:\project\Contract

##多数据源的配置，需要引用renren-dynamic-datasource
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://redis:1433;DatabaseName=security_enterprise
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://redis:5432/security_enterprise
#      username: postgres
#      password: 123456